name: Env harjoitus
on: workflow_dispatch
env:
  APP_NAME: MathCounter
  APP_VERSION: v1.0.2
jobs:
  sentence-job:
    runs-on: ubuntu-latest
    steps: 
        -  run: echo "Your app name is $APP_NAME and version is $APP_VERSION
