name: Tehtävä 1
on: workflow_dispatch
permissions:
  contents: write
jobs:
  container-job:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.63.0-noble
    steps:
      - uses: actions/checkout@v7
      - name: First step
        id: first
        run: |
          npm ci
          npm test -- test1 > testi1.txt || true
      - name: Second step
        id: second
        run: npm test -- test2 > testi2.txt
      - name: Push into git
        if: failure() || success()
        id: push
        run: |
          git config --global --add safe.directory '.'
          git config --global user.name 'DefalDonut'
          git config --global user.email 'tsaily24@students.oamk.fi'
          git add test1.txt testi2.txt
          git commit -m "File created" || true
          git push
      - name: Failure
        if: failure()
        run: echo "Testit epäonnistuivat"
